trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    submodules: true
  - task: Bash@3
    inputs: 
      targetType: "inline"
      script: |
        cd client
        echo "VITE_API_URL=$(api_url)" > .env
        cat .env
    displayName: "Create env file"

  - task: AzureStaticWebApp@0
    inputs:
      app_location: '/client'
      app_build_command: 'npm run build'
      output_location: '/dist'
      azure_static_web_apps_api_token: '$(deployment_token)'