# Use root/example as user/password credentials
version: '3.1'

services:

   mariadb:
    container_name: mariaDB
    image: docker.io/bitnami/mariadb:10.6
    ports:
      - '3306:3306'
    volumes:
      - 'mariaDB_data:/bitnami/mariaDB'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_DATABASE=school-planner
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariaDB/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
   phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8083:80
    environment:
      - PMA_ARBITRARY=1
volumes:
  mariaDB_data:
    driver: local
